spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

jwt:
  header: Authorization
  secret: eyJhbGciOiJIUzUxMiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY3OTI5MzQwNSwiaWF0IjoxNjc5MjkzNDA1fQ.l5pfVbj0OWpSBxUGlhPMn9IbUt14vDU8ozbwaBMnKapUNKKCBRmpWVm8Hmopg-UBk0RYaExQRLx8IM6VzH9vAQ

logging:
  level:
    org.hibernate.sql: debug

springdoc:
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
  pre-loading-enabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8